
### obtener todos los tipos de propiedad
GET http://localhost:3000/api/tipopropiedades

### crear un nuevo tipo de propiedad
# @name createTipoPropiedad
POST http://localhost:3000/api/tipopropiedades
Content-Type: application/json

{
    "id": 1,
    "nombre": "Departamento",
    "descripcion": "Monoambiente",
    "estado": "Activo"
}

### ID
@id = {{createTipoPropiedad.response.body.data.id}}

### obtener un tipo de propiedad por id
GET http://localhost:3000/api/tipopropiedades/{{id}}

### modificar un tipo de propiedad (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tipopropiedades/{{id}}
Content-Type: application/json

{
    "id": 1,
    "descripcion": "Dos habitaciones"
}

# @name createTipoPropiedadToDelete
POST http://localhost:3000/api/tipopropiedades
Content-Type: application/json

{
    "id": 2,
    "descripcion": "Tres ambientes"
}

### borrar un tipo de propiedad
@idToDelete = {{createTipoPropiedadToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/tipopropiedades/{{idToDelete}}